# Generated by Django 4.2.7 on 2023-12-06 18:10

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_alter_profileuser_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region='RU'),
        ),
    ]
